/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#ff7cf5",
        "surface": "#120c16",
        "inverse-primary": "#aa00aa",
        "primary-dim": "#ff51fa",
        "on-tertiary": "#290067",
        "on-secondary-fixed-variant": "#005964",
        "on-primary-fixed": "#000000",
        "outline": "#7c727f",
        "tertiary-container": "#7000ff",
        "surface-tint": "#ff7cf5",
        "inverse-on-surface": "#5a525e",
        "tertiary": "#ac89ff",
        "surface-dim": "#120c16",
        "primary-container": "#ff5af9",
        "on-tertiary-fixed": "#1f0052",
        "outline-variant": "#4d4551",
        "on-secondary-container": "#e8fbff",
        "on-primary-container": "#440044",
        "primary-fixed-dim": "#ff1cfe",
        "error-container": "#a70138",
        "tertiary-dim": "#874cff",
        "on-background": "#f7eaf9",
        "on-tertiary-container": "#f8f1ff",
        "tertiary-fixed-dim": "#b190ff",
        "secondary-fixed": "#26e6ff",
        "background": "#120c16",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#17111c",
        "secondary-container": "#006875",
        "surface-container": "#1e1723",
        "inverse-surface": "#fff7fd",
        "on-primary": "#580058",
        "secondary-fixed-dim": "#00d7f0",
        "on-secondary-fixed": "#003a42",
        "on-secondary": "#004d57",
        "surface-variant": "#2b2231",
        "error": "#ff6e84",
        "tertiary-fixed": "#bda1ff",
        "secondary-dim": "#00d4ec",
        "on-surface-variant": "#b2a7b6",
        "secondary": "#00e3fd",
        "primary-fixed": "#ff5af9",
        "on-surface": "#f7eaf9",
        "surface-container-highest": "#2b2231",
        "on-primary-fixed-variant": "#540054",
        "surface-container-high": "#251d2a",
        "on-tertiary-fixed-variant": "#4700a7",
        "error-dim": "#d73357",
        "on-error-container": "#ffb2b9",
        "surface-bright": "#322838",
        "on-error": "#490013"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}